# 1=arange


In [1]:
import numpy as np

In [2]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
np.arange(4,12)

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
np.arange(132,150)

array([132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149])

In [5]:
np.arange(12,2,6)

array([], dtype=int32)

In [6]:
np.arange(2,6,12)

array([2])

In [7]:
np.arange(10,16)

array([10, 11, 12, 13, 14, 15])

In [8]:
np.arange(0,1,2,)

array([0])

In [9]:
np.arange(3,4,6)

array([3])

In [10]:
np.arange(1500)

array([   0,    1,    2, ..., 1497, 1498, 1499])

In [11]:
np.arange(12,20,30)

array([12])

# 2 = empty

In [12]:
#.empty

In [13]:
np.empty(2)

array([-1.68077484e+028, -3.06769768e-304])

In [14]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.empty(20)

array([1.44694655e-311, 6.27463370e-322, 0.00000000e+000, 0.00000000e+000,
       8.01097888e-307, 5.30276956e+180, 1.02941932e-071, 6.98476580e-076,
       3.45696583e-086, 3.35809597e-143, 6.01433264e+175, 6.93885958e+218,
       5.56218858e+180, 3.94356143e+180, 8.77515706e-071, 9.04436048e-067,
       9.12443864e+169, 6.12956775e-062, 5.22683369e-143, 1.50008929e+248])

In [16]:
np.empty(10)

array([1.44694717e-311, 2.17388884e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.16095484e-028, 7.52736939e+252, 4.50603893e-144,
       4.82412328e+228, 1.04718130e-142])

In [56]:
np.empty((10,2)) 

array([[1.44694655e-311, 6.27463370e-322],
       [0.00000000e+000, 0.00000000e+000],
       [8.01097888e-307, 5.30276956e+180],
       [1.02941932e-071, 6.98476580e-076],
       [3.45696583e-086, 3.35809597e-143],
       [6.01433264e+175, 6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180],
       [8.77515706e-071, 9.04436048e-067],
       [9.12443864e+169, 6.12956775e-062],
       [5.22683369e-143, 1.50008929e+248]])

In [18]:
np.empty((5,2))

array([[1.44694717e-311, 2.17388884e-322],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 1.16095484e-028],
       [7.52736939e+252, 4.50603893e-144],
       [4.82412328e+228, 1.04718130e-142]])

In [19]:
np.empty((2))

array([1.68077484e+028, 3.06769768e-304])

In [20]:
np.empty((5,23))     #5=row   and   23=column 

array([[1.44691561e-311, 1.44691562e-311, 1.44691562e-311,
        1.44691561e-311, 1.44691562e-311, 1.44691562e-311,
        1.44691562e-311, 1.44691561e-311, 1.44691562e-311,
        1.44691561e-311, 1.44691561e-311, 1.44691592e-311,
        1.44691561e-311, 1.44691561e-311, 1.44691561e-311,
        1.44691562e-311, 1.44691561e-311, 1.44691561e-311,
        1.44691562e-311, 1.44691561e-311, 1.44691561e-311,
        1.44691562e-311, 1.44691562e-311],
       [1.44691561e-311, 1.44691561e-311, 1.44691568e-311,
        1.44691562e-311, 1.44691561e-311, 1.44691562e-311,
        1.44691581e-311, 1.44692189e-311, 1.44693685e-311,
        1.44692223e-311, 1.44693686e-311, 1.44692228e-311,
        1.44692227e-311, 1.44693686e-311, 1.44692188e-311,
        1.44693601e-311, 1.44692227e-311, 1.44692186e-311,
        1.44692186e-311, 1.44692188e-311, 1.44692188e-311,
        1.44693685e-311, 1.44693686e-311],
       [1.44692187e-311, 1.44693686e-311, 1.44692189e-311,
        1.44692224e-311, 1.44

# 3=Linespace

In [21]:
#linespace
import numpy as np

In [22]:
np.linspace(2,6,8)

array([2.        , 2.57142857, 3.14285714, 3.71428571, 4.28571429,
       4.85714286, 5.42857143, 6.        ])

In [23]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [24]:
np.linspace(2,1)

array([2.        , 1.97959184, 1.95918367, 1.93877551, 1.91836735,
       1.89795918, 1.87755102, 1.85714286, 1.83673469, 1.81632653,
       1.79591837, 1.7755102 , 1.75510204, 1.73469388, 1.71428571,
       1.69387755, 1.67346939, 1.65306122, 1.63265306, 1.6122449 ,
       1.59183673, 1.57142857, 1.55102041, 1.53061224, 1.51020408,
       1.48979592, 1.46938776, 1.44897959, 1.42857143, 1.40816327,
       1.3877551 , 1.36734694, 1.34693878, 1.32653061, 1.30612245,
       1.28571429, 1.26530612, 1.24489796, 1.2244898 , 1.20408163,
       1.18367347, 1.16326531, 1.14285714, 1.12244898, 1.10204082,
       1.08163265, 1.06122449, 1.04081633, 1.02040816, 1.        ])

In [25]:
np.linspace(6,8)

array([6.        , 6.04081633, 6.08163265, 6.12244898, 6.16326531,
       6.20408163, 6.24489796, 6.28571429, 6.32653061, 6.36734694,
       6.40816327, 6.44897959, 6.48979592, 6.53061224, 6.57142857,
       6.6122449 , 6.65306122, 6.69387755, 6.73469388, 6.7755102 ,
       6.81632653, 6.85714286, 6.89795918, 6.93877551, 6.97959184,
       7.02040816, 7.06122449, 7.10204082, 7.14285714, 7.18367347,
       7.2244898 , 7.26530612, 7.30612245, 7.34693878, 7.3877551 ,
       7.42857143, 7.46938776, 7.51020408, 7.55102041, 7.59183673,
       7.63265306, 7.67346939, 7.71428571, 7.75510204, 7.79591837,
       7.83673469, 7.87755102, 7.91836735, 7.95918367, 8.        ])

In [26]:
np.linspace(8,2)

array([8.        , 7.87755102, 7.75510204, 7.63265306, 7.51020408,
       7.3877551 , 7.26530612, 7.14285714, 7.02040816, 6.89795918,
       6.7755102 , 6.65306122, 6.53061224, 6.40816327, 6.28571429,
       6.16326531, 6.04081633, 5.91836735, 5.79591837, 5.67346939,
       5.55102041, 5.42857143, 5.30612245, 5.18367347, 5.06122449,
       4.93877551, 4.81632653, 4.69387755, 4.57142857, 4.44897959,
       4.32653061, 4.20408163, 4.08163265, 3.95918367, 3.83673469,
       3.71428571, 3.59183673, 3.46938776, 3.34693878, 3.2244898 ,
       3.10204082, 2.97959184, 2.85714286, 2.73469388, 2.6122449 ,
       2.48979592, 2.36734694, 2.24489796, 2.12244898, 2.        ])

# 4=Axis

In [27]:
#axis=0
#axis=1

In [28]:
arr1 =np.array([[1,2,3]])

In [29]:
arr1

array([[1, 2, 3]])

In [30]:
arr1 =np.array([[1,2,3],[2,3,4]])

In [31]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [32]:
arr1 =np.array([[1,2,3],[2,3,4],[5,6,7]])

In [33]:
arr1

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [34]:
arr1 =np.array([1,2,3])

In [35]:
arr1

array([1, 2, 3])

In [36]:
type(arr1)

numpy.ndarray

In [37]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [38]:
arr2 = np.array([[7,8,9],[3,5,9]])

In [39]:
print(arr1+arr2)

[[ 8 10 12]
 [ 7 10 15]]


In [40]:
arr1 = np.array([[7,8,9],[3,5,9],[1,2,3]])
arr2 = np.array([[7,8,9],[3,5,9],[2,3,4]])

In [41]:
print(arr1+arr2)

[[14 16 18]
 [ 6 10 18]
 [ 3  5  7]]


In [42]:
arr1.ndim

2

In [43]:
arr1=np.array([[[7,8,9],[3,5,9],[1,2,3],[5,6,6]]])
arr2=np.array([[[7,8,9],[3,5,9],[2,3,4],[3,5,7]]])

In [44]:
print(arr1+arr2)

[[[14 16 18]
  [ 6 10 18]
  [ 3  5  7]
  [ 8 11 13]]]


In [45]:
arr1,arr2.ndim 

(array([[[7, 8, 9],
         [3, 5, 9],
         [1, 2, 3],
         [5, 6, 6]]]),
 3)

In [46]:
arr1.sum(axis=1)

array([[16, 21, 27]])

In [47]:
arr2.sum(axis=0)

array([[7, 8, 9],
       [3, 5, 9],
       [2, 3, 4],
       [3, 5, 7]])

In [48]:
k1=np.array([[[1,2,3],[3,4,5],[4,5,6]]])

In [49]:
k1

array([[[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]])

In [50]:
k1.sum(axis=0)

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [51]:
k1.sum(axis=1)

array([[ 8, 11, 14]])

In [52]:
k1

array([[[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]])

In [53]:
s=np.array([[33,44,65],[43,34,5],[7,99,6]])

In [54]:
s

array([[33, 44, 65],
       [43, 34,  5],
       [ 7, 99,  6]])

In [55]:
s.T

array([[33, 43,  7],
       [44, 34, 99],
       [65,  5,  6]])