# Libararies

# Numpy,Pandas,matplotlib,seabone

# (Numpy)

In [1]:
import numpy as np

In [2]:
#array 0,1,2,3

In [16]:
#1-D 
import numpy as np
myarr = np.array([1,2,35])

In [17]:
print(myarr)

[ 1  2 35]


In [20]:
type(myarr)

numpy.ndarray

In [24]:
#1-D
arr = np.array([1,])

In [25]:
arr

array([1])

In [26]:
type(myarr)

numpy.ndarray

In [27]:
myarr.ndim

1

In [28]:
#2-D
myarr = np.array([[1,2,3,4],[5,6,7,8]])

In [30]:
myarr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
type(myarr)

numpy.ndarray

In [32]:
myarr.ndim

2

In [33]:
myarr = np.array([[1,2,3,4],[5,6,7,8,9]])

<ipython-input-33-d3ca5491d51e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  myarr = np.array([[1,2,3,4],[5,6,7,8,9]])


In [34]:
myarr = np.array([[1,2,3,4],[5,6,7,8],[4,5,6,7]])

In [35]:
myarr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 5, 6, 7]])

In [36]:
type(myarr)

numpy.ndarray

In [37]:
myarr.ndim

2

In [38]:
myarr = np.array([[1,2,3,4],[5,6,7,8],[4,5,6,7],[23,3,5,45]])

In [39]:
myarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 4,  5,  6,  7],
       [23,  3,  5, 45]])

In [40]:
type(myarr)

numpy.ndarray

In [41]:
myarr.ndim

2

In [45]:
myarr = np.array([0])

In [46]:
myrr

NameError: name 'myrr' is not defined

In [53]:
#3-D
x = np.array([[[1,2,3],[2,3,3],[6,7,8]]])

In [55]:
x

array([[[1, 2, 3],
        [2, 3, 3],
        [6, 7, 8]]])

In [56]:
type(x)

numpy.ndarray

In [57]:
x.ndim

3

In [60]:

x = np.array([[[1,2,3,0],[2,3,3,0],[6,7,8,0],[6,7,8,0]]])

In [61]:
x

array([[[1, 2, 3, 0],
        [2, 3, 3, 0],
        [6, 7, 8, 0],
        [6, 7, 8, 0]]])

In [62]:
type(x)

numpy.ndarray

In [63]:
x.ndim

3

In [66]:

x = np.array([[[[[1,2,3],[2,3,3],[6,7,8]]]]])

In [67]:
x.ndim

5

\\\\\Totally depand on curly brackets\\\\

# Fuction of libraries?


In [1]:
#Zeros,Ones
#arange
#Empty
#Identity
# linespace
# empty
#axis0,axis1
# Sum function with axis
#transpose matrix
# min & max in array ----> argmax,argmin,argsort (with axis also)
#Matrix operation
# np.sqrt,sum,max,min
#finding the data using where


In [68]:
#zeros
np.zeros(1)

array([0.])

In [70]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
np.zeros((2,2,10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [75]:
np.zeros(2)

array([0., 0.])

In [76]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [81]:
np.zeros(3,3,3)

TypeError: Cannot interpret '3' as a data type

In [77]:
#ones
np.ones(1)

array([1.])

In [78]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [80]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [82]:
np.ones((100))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
#identity matrix(0 or 1)
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [85]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
np.identity((2,5))

TypeError: 'tuple' object cannot be interpreted as an integer

# PRACTICES

In [7]:
import numpy as np
myarr = np.array([2,3,4,5,])

In [8]:
myarr

array([2, 3, 4, 5])

In [9]:
type(myarr)

numpy.ndarray

In [10]:
myarr.ndim

1

In [15]:
myarr =np.array([[2,3,4,5,],[5,6,7,8]])
print(myarr)

[[2 3 4 5]
 [5 6 7 8]]


In [12]:
type(myarr)

numpy.ndarray

In [13]:
myarr.ndim

2

In [17]:
myarr =np.array([[2,3,4,5,],[5,6,7,8],[6,4,9,6]])

In [18]:
myarr

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [6, 4, 9, 6]])

In [20]:
myarr =np.array([[2,3,4,5,],[5,6,7,8],[6,4,9,6],[0,9,8,7]])

In [21]:
myarr

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [6, 4, 9, 6],
       [0, 9, 8, 7]])

In [22]:
myarr.ndim

2

In [23]:
myarr =np.array([[[2,3,4,5,],[5,6,7,8],[6,4,9,6],[0,9,8,7]]])

In [24]:
myarr

array([[[2, 3, 4, 5],
        [5, 6, 7, 8],
        [6, 4, 9, 6],
        [0, 9, 8, 7]]])

In [25]:
myarr.ndim

3

In [26]:
#Library function
#1= zeros
#2=ones

SyntaxError: cannot assign to literal (<ipython-input-26-738a3b8e3a9a>, line 2)

In [27]:
#zeros
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
np.zeros(30)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
type(np.zeros)

builtin_function_or_method

In [40]:
np.ones(2)

array([1., 1.])

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [49]:
type(np.ones)

function

In [51]:
np.ones((2,3,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [52]:
np.twos(2)

AttributeError: module 'numpy' has no attribute 'twos'

In [53]:
np.ones(2)

array([1., 1.])